name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  test:
    runs-on: macos-15  # Use macOS 15 (Sequoia) runner which should have Xcode 16
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Select Xcode 16
        run: |
          # List available Xcode versions for debugging
          echo "Available Xcode versions:"
          ls /Applications | grep Xcode || true
          
          # Find and select the latest Xcode 16.x version (e.g., 16.0, 16.1, 16.4, etc.)
          # sort -V does version sorting, so 16.4 > 16.1 > 16.0
          XCODE_16=$(ls /Applications | grep -E "Xcode_16\.[0-9]+\.app" | sort -V | tail -n1)
          
          if [ -n "$XCODE_16" ]; then
            echo "Selecting $XCODE_16"
            sudo xcode-select -s /Applications/$XCODE_16/Contents/Developer
          elif [ -d "/Applications/Xcode.app" ]; then
            echo "No Xcode 16.x found, using default Xcode.app"
            sudo xcode-select -s /Applications/Xcode.app/Contents/Developer
          else
            echo "Error: No suitable Xcode installation found"
            exit 1
          fi
          
          # Verify selected version
          echo "Selected Xcode version:"
          xcodebuild -version
          echo "Swift version:"
          swift --version
      
      - name: Build
        run: |
          swift build -c release --verbose
      
      - name: Run Tests
        run: |
          swift test --verbose
      
      - name: Build Universal Binary
        run: |
          chmod +x build-universal.sh
          ./build-universal.sh
      
      - name: Verify Binary
        run: |
          ./xcodeproj-cli --version
          file xcodeproj-cli
          lipo -info xcodeproj-cli
      
      - name: Test Binary Commands
        run: |
          # Test help command
          ./xcodeproj-cli --help
          
          # Test validation on test project
          ./xcodeproj-cli --project Tests/xcodeproj-cliTests/TestResources/TestProject.xcodeproj validate