name: Enhanced Build and Release

on:
  push:
    tags:
      - 'v*'  # Triggers on version tags like v1.0.0, v1.1.0, etc.

jobs:
  build-and-release:
    runs-on: macos-latest
    
    permissions:
      contents: write  # Required for creating releases
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Swift
        uses: swift-actions/setup-swift@v2
        with:
          swift-version: "5.9"
      
      - name: Get version from tag
        run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
        
      - name: Update version in source
        run: |
          # Update version number in CLIInterface.swift
          sed -i '' 's/let VERSION = ".*"/let VERSION = "${VERSION#v}"/' Sources/xcodeproj-cli/CLI/CLIInterface.swift
          
      - name: Build universal binary
        run: |
          # Build universal binary using our build script
          chmod +x build-universal.sh
          ./build-universal.sh
          
      - name: Verify binary
        run: |
          # Test that binary works and shows correct version
          ./xcodeproj-cli --version
          file xcodeproj-cli
          lipo -info xcodeproj-cli
          
      - name: Create archive
        run: |
          # Create tar.gz archive for Homebrew
          tar -czf xcodeproj-cli-${{ env.VERSION }}-macos.tar.gz xcodeproj-cli
          
          # Calculate SHA256 for Homebrew formula
          echo "SHA256=$(shasum -a 256 xcodeproj-cli-${{ env.VERSION }}-macos.tar.gz | cut -d' ' -f1)" >> $GITHUB_ENV
          
      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.VERSION }}
          name: Release ${{ env.VERSION }}
          body: |
            ## xcodeproj-cli ${{ env.VERSION }}
            
            ### Installation
            
            **Homebrew (Recommended):**
            ```bash
            brew tap tolo/xcodeproj
            brew install xcodeproj-cli
            ```
            
            **Direct Download:**
            1. Download the `xcodeproj-cli-${{ env.VERSION }}-macos.tar.gz` file
            2. Extract: `tar -xzf xcodeproj-cli-${{ env.VERSION }}-macos.tar.gz`
            3. Move to PATH: `sudo mv xcodeproj-cli /usr/local/bin/`
            4. Make executable: `chmod +x /usr/local/bin/xcodeproj-cli`
            
            ### What's New
            
            See [CHANGELOG.md](./CHANGELOG.md) for detailed changes.
            
            ### System Requirements
            
            - macOS 10.15+ (Catalina or later)
            - Both Intel and Apple Silicon Macs are supported
            - No additional dependencies required
            
            ### SHA256 Checksum
            ```
            ${{ env.SHA256 }}  xcodeproj-cli-${{ env.VERSION }}-macos.tar.gz
            ```
            
          files: |
            xcodeproj-cli-${{ env.VERSION }}-macos.tar.gz
          generate_release_notes: false
          draft: false
          prerelease: false
          
      - name: Update Homebrew Formula
        env:
          HOMEBREW_TAP_TOKEN: ${{ secrets.HOMEBREW_TAP_TOKEN }}
        run: |
          # This step automatically updates the Homebrew formula
          # Requires a personal access token with repo scope for the tap repository
          
          if [ -n "$HOMEBREW_TAP_TOKEN" ]; then
            echo "🍺 Updating Homebrew formula..."
            
            # Clone tap repository
            git config --global user.name "GitHub Actions"
            git config --global user.email "actions@github.com"
            git clone https://x-access-token:${HOMEBREW_TAP_TOKEN}@github.com/tolo/homebrew-xcodeproj.git tap-repo
            
            # Update formula
            cd tap-repo
            if [ -f "Formula/xcodeproj-cli.rb" ]; then
              sed -i '' "s/version \".*\"/version \"${VERSION#v}\"/" Formula/xcodeproj-cli.rb
              sed -i '' "s|url \".*\"|url \"https://github.com/tolo/xcodeproj-cli/releases/download/${{ env.VERSION }}/xcodeproj-cli-${{ env.VERSION }}-macos.tar.gz\"|" Formula/xcodeproj-cli.rb
              sed -i '' "s/sha256 \".*\"/sha256 \"${{ env.SHA256 }}\"/" Formula/xcodeproj-cli.rb
              
              # Commit and push
              git add Formula/xcodeproj-cli.rb
              git commit -m "Update xcodeproj-cli to ${{ env.VERSION }}"
              git push
              
              echo "✅ Homebrew formula updated automatically!"
            else
              echo "⚠️ Formula not found, manual update required"
            fi
          else
            echo "ℹ️ HOMEBREW_TAP_TOKEN not set, skipping automatic formula update"
            echo "Manual update required for Homebrew formula"
          fi
          
      - name: Show Manual Update Info
        if: env.HOMEBREW_TAP_TOKEN == ''
        run: |
          echo "========================================="
          echo "📦 Homebrew Formula Information"
          echo "========================================="
          echo ""
          echo "Update your Homebrew formula with:"
          echo "  version: ${VERSION#v}"
          echo "  url: https://github.com/tolo/xcodeproj-cli/releases/download/${{ env.VERSION }}/xcodeproj-cli-${{ env.VERSION }}-macos.tar.gz"
          echo "  sha256: ${{ env.SHA256 }}"
          echo ""
          echo "Binary details:"
          echo "  Size: $(du -h xcodeproj-cli | cut -f1)"
          echo "  Architectures: $(lipo -info xcodeproj-cli | cut -d: -f2-)"
          echo ""