name: Build and Release

on:
  push:
    tags:
      - 'v*'  # Triggers on version tags like v1.0.0, v1.1.0, etc.

jobs:
  build-and-release:
    runs-on: macos-latest
    
    permissions:
      contents: write  # Required for creating releases
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Swift
        uses: swift-actions/setup-swift@v2
        with:
          swift-version: "5.9"
      
      - name: Get version from tag
        run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
        
      - name: Update version in source
        run: |
          # Update version number in main.swift
          sed -i '' 's/XcodeProj CLI v[0-9]\+\.[0-9]\+\.[0-9]\+/XcodeProj CLI ${{ env.VERSION }}/' Sources/xcodeproj-cli/main.swift
          
      - name: Build universal binary
        run: |
          # Build universal binary using our build script
          chmod +x build-universal.sh
          ./build-universal.sh
          
      - name: Verify binary
        run: |
          # Test that binary works and shows correct version
          ./xcodeproj-cli --version
          file xcodeproj-cli
          lipo -info xcodeproj-cli
          
      - name: Create archive
        run: |
          # Create tar.gz archive for Homebrew
          tar -czf xcodeproj-cli-${{ env.VERSION }}-macos.tar.gz xcodeproj-cli
          
          # Calculate SHA256 for Homebrew formula
          echo "SHA256=$(shasum -a 256 xcodeproj-cli-${{ env.VERSION }}-macos.tar.gz | cut -d' ' -f1)" >> $GITHUB_ENV
          
      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.VERSION }}
          name: Release ${{ env.VERSION }}
          body: |
            ## xcodeproj-cli ${{ env.VERSION }}
            
            ### Installation
            
            **Homebrew (Recommended):**
            ```bash
            brew tap tolo/xcodeproj
            brew install xcodeproj-cli
            ```
            
            **Direct Download:**
            1. Download the `xcodeproj-cli-${{ env.VERSION }}-macos.tar.gz` file
            2. Extract: `tar -xzf xcodeproj-cli-${{ env.VERSION }}-macos.tar.gz`
            3. Move to PATH: `sudo mv xcodeproj-cli /usr/local/bin/`
            4. Make executable: `chmod +x /usr/local/bin/xcodeproj-cli`
            
            ### What's New
            
            See [CHANGELOG.md](./CHANGELOG.md) for detailed changes.
            
            ### System Requirements
            
            - macOS 10.15+ (Catalina or later)
            - Both Intel and Apple Silicon Macs are supported
            - No additional dependencies required
            
            ### SHA256 Checksum
            ```
            ${{ env.SHA256 }}  xcodeproj-cli-${{ env.VERSION }}-macos.tar.gz
            ```
            
          files: |
            xcodeproj-cli-${{ env.VERSION }}-macos.tar.gz
          generate_release_notes: false
          draft: false
          prerelease: false
          
      - name: Show Homebrew Formula Info
        run: |
          echo "========================================="
          echo "📦 Homebrew Formula Information"
          echo "========================================="
          echo ""
          echo "Update your Homebrew formula with:"
          echo "  version: ${{ env.VERSION }}"
          echo "  url: https://github.com/tolo/xcodeproj-cli/releases/download/${{ env.VERSION }}/xcodeproj-cli-${{ env.VERSION }}-macos.tar.gz"
          echo "  sha256: ${{ env.SHA256 }}"
          echo ""
          echo "Binary details:"
          echo "  Size: $(du -h xcodeproj-cli | cut -f1)"
          echo "  Architectures: $(lipo -info xcodeproj-cli | cut -d: -f2-)"
          echo ""